version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for container images
  - package-ecosystem: "docker"
    directory: "/containers"
    schedule:
      interval: "monthly"
