# Copyright (c) 2021 Leorize <leorize+oss@disroot.org>
#
# This file is licensed under the terms of the MIT license. See "license.txt"
# included in this distribution for more information.

# --- Image used for building the compiler

# The name of the Debian release being used.
#
# This image tracks LTS releases.
ARG debian_release=buster

FROM docker.io/debian:$debian_release-slim as builder

# Respecified here so that the variable can be used by this image
ARG debian_release

# Add the NodeSource keyring to APT
ADD --chmod=644 https://deb.nodesource.com/gpgkey/nodesource.gpg.key /etc/apt/trusted.gpg.d/nodesource.asc

# Install ca-certificates in order to download from NodeSource.
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
         --no-install-recommends \
         ca-certificates \
    # Add the NodeSource sources to APT
    && echo "deb [signed-by=/etc/apt/trusted.gpg.d/nodesource.asc] https://deb.nodesource.com/node_16.x $debian_release main" > /etc/apt/sources.list.d/nodesource.list \
    # Update APT then install compiler build dependencies
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
         --no-install-recommends \
         # Required for building the compiler
         gcc \
         g++ \
         # Required for building C stuff
         libc-dev \
         # Required for building csources
         make \
         # Required for retrieving source information
         git \
         # Required for running build script
         python3 \
         # Required for building docs
         nodejs \
    && rm -rf /var/lib/apt/lists/*

# --- Image used for testing the compiler

FROM builder as tester

# Install additional dependencies for compiler tests
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
      --no-install-recommends \
      # Required by Boehm GC tests
      libgc-dev \
      # Required for ARC/ORC memory leak tests
      libc6-dbg \
      valgrind \
      # Required for tgetprotobyname.nim
      netbase \
    # Remove APT lists after we are done
    && rm -rf /var/lib/apt/lists/*
