name: Build container images

on:
  push:
    branches:
      - main
    tags:
      - '*'

  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, test and push
    runs-on: ubuntu-latest

    services:
      # Use a local registry to store images while they are tested
      registry:
        image: registry:2
        ports:
          - 5000:5000

    env:
      builder_img: ghcr.io/${{ github.repository_owner }}/nimskull-builder
      builder_test_tag: localhost:5000/nimskull-builder:test
      tester_img: ghcr.io/${{ github.repository_owner }}/nimskull-tester
      tester_test_tag: localhost:5000/nimskull-tester:test

      # List of Docker platforms to build images for
      targets: linux/amd64,linux/arm64,linux/arm/v7

      # Nimskull commit to test the containers with
      nimskull_test_commit: 85f6cacd4ca0e6a3f3464c21e15c0ad98979b731

    # Grant write permissions to packages
    permissions:
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate metadata for the builder image
        id: builder_meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: |
            ${{ env.builder_img }}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=ref,event=pr

      - name: Generate metadata for the tester image
        id: tester_meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: |
            ${{ env.tester_img }}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=ref,event=pr

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
        with:
          # This is done so that builders can access the local registry
          driver-opts: network=host

      - name: Build and load tester image
        uses: docker/build-push-action@v2.8.0
        with:
          context: ./containers
          platforms: ${{ env.targets }}
          push: true
          tags: ${{ env.tester_test_tag }}
          target: tester
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and load builder image
        uses: docker/build-push-action@v2.8.0
        with:
          context: ./containers
          platforms: ${{ env.targets }}
          push: true
          tags: ${{ env.builder_test_tag }}
          target: builder
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # TODO: Test the image on nimskull

      - name: Login to Github registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Push tester image
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v2.8.0
        with:
          context: ./containers
          platforms: ${{ env.targets }}
          push: true
          tags: ${{ steps.tester_meta.outputs.tags }}
          labels: ${{ steps.tester_meta.outputs.labels }}
          target: tester
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Push builder image
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v2.8.0
        with:
          context: ./containers
          platforms: ${{ env.targets }}
          push: true
          tags: ${{ steps.builder_meta.outputs.tags }}
          labels: ${{ steps.builder_meta.outputs.labels }}
          target: builder
          cache-from: type=gha
          cache-to: type=gha,mode=max
